//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETTB
    {
        public int MATB { get; set; }
        public string TENTB { get; set; }
        public Nullable<double> GIATHANH { get; set; }
        public string MANHINH { get; set; }
        public string HDH { get; set; }
        public string Camerasau { get; set; }
        public string cameratruoc { get; set; }
        public string chip { get; set; }
        public string ram { get; set; }
        public string bonho { get; set; }
        public string sim { get; set; }
        public string pinxac { get; set; }
        public string HINHANH1 { get; set; }
        public string HINHANH2 { get; set; }
        public string HINHANH3 { get; set; }
        public string HINHANH4 { get; set; }
        public string HINHANH5 { get; set; }
        public string HINHANH6 { get; set; }
        public string chitiet { get; set; }
    
        public virtual THIETBI THIETBI { get; set; }
    }
}
