//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chucVu
    {
        public chucVu()
        {
            this.accounts = new HashSet<account>();
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int maCV { get; set; }
        public string tenCV { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
