//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int maHD { get; set; }
        public string mail { get; set; }
        public string sodienthoai { get; set; }
        public string hoten { get; set; }
        public string diachi { get; set; }
        public string quanHuyen { get; set; }
        public string tinhTP { get; set; }
        public string hinhThucTT { get; set; }
        public Nullable<int> MATB { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
    
        public virtual THIETBI THIETBI { get; set; }
    }
}
