//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC_demoEntities : DbContext
    {
        public MVC_demoEntities()
            : base("name=MVC_demoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<account> accounts { get; set; }
        public DbSet<Carosel> Carosels { get; set; }
        public DbSet<CHITIETTB> CHITIETTBs { get; set; }
        public DbSet<chucVu> chucVus { get; set; }
        public DbSet<HangSanXuat> HangSanXuats { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<loaiTB> loaiTBs { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<THIETBI> THIETBIs { get; set; }
    }
}
