//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int maNV { get; set; }
        public string tenNV { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string diaChi { get; set; }
        public Nullable<System.DateTime> ngayVaoLam { get; set; }
        public string hinhanh { get; set; }
        public Nullable<int> luong { get; set; }
        public Nullable<int> maCV { get; set; }
        public string email { get; set; }
        public string soDT { get; set; }
    
        public virtual chucVu chucVu { get; set; }
    }
}
