//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIETBI
    {
        public THIETBI()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int MATB { get; set; }
        public string TENTB { get; set; }
        public Nullable<double> GIATHANH { get; set; }
        public string HINHANH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> LOAITB { get; set; }
        public Nullable<int> MAHSX { get; set; }
    
        public virtual CHITIETTB CHITIETTB { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual loaiTB loaiTB1 { get; set; }
    }
}
